# Generated by Django 4.2.17 on 2025-01-11 18:24

import datetime
from django.db import migrations, models
import scheduler.validators


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="duration",
            field=models.DurationField(
                default=datetime.timedelta(seconds=3600),
                verbose_name="Appointment Duration",
            ),
        ),
        migrations.AddField(
            model_name="snf",
            name="hour_closes",
            field=models.TimeField(
                default=datetime.time(17, 0), verbose_name="Closing Hour"
            ),
        ),
        migrations.AddField(
            model_name="snf",
            name="hour_opens",
            field=models.TimeField(
                default=datetime.time(8, 0), verbose_name="Opening Hour"
            ),
        ),
        migrations.AddField(
            model_name="snf",
            name="max_concurrent_appointments",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Maximum Concurrent Appointments"
            ),
        ),
        migrations.AddField(
            model_name="snf",
            name="phone",
            field=models.CharField(
                default="000-000-0000", max_length=15, verbose_name="Phone Number"
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="date",
            field=models.DateTimeField(
                validators=[
                    scheduler.validators.CustomValidators.validate_holiday,
                    scheduler.validators.CustomValidators.validate_not_weekend,
                ],
                verbose_name="Appointment Date",
            ),
        ),
    ]
