# Generated by Django 4.2.18 on 2025-01-17 18:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "scheduler",
            "0002_appointment_duration_snf_hour_closes_snf_hour_opens_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="snf",
            name="hour_closes",
            field=models.TimeField(
                default=datetime.time(17, 0),
                error_messages={"required": "Closing hour is required."},
                verbose_name="Closing Hour",
            ),
        ),
        migrations.AlterField(
            model_name="snf",
            name="hour_opens",
            field=models.TimeField(
                default=datetime.time(8, 0),
                error_messages={"required": "Opening hour is required."},
                verbose_name="Opening Hour",
            ),
        ),
    ]
